title: Ricardo Guzman
description: Your personal academic site.
theme: just-the-docs
url: https://guzmanricardo.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
